<a href="https://colab.research.google.com/github/nityanandkumarm/Python/blob/main/Python_tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([0.5, 0.6,0.2,0.1, 0.8, 0.9])
A=A.reshape(1, 6)
print(A)
print(A.shape)
print(A[0,1])

[[0.5 0.6 0.2 0.1 0.8 0.9]]
(1, 6)
0.6


In [ ]:
import numpy as np
A= np.zeros((1,5))
print(A)

[[0. 0. 0. 0. 0.]]


In [ ]:
A>0.5

array([[False, False, False, False, False]])

In [ ]:
import numpy as np
a = np.random.randn(12288, 150) 
b = np.random.randn(150, 45) 
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [ ]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c,c.shape)

[[-2.94578362 -3.99396902 -0.48875779]
 [-0.01176191  0.02197683 -0.06095823]
 [ 0.23236801  0.18547493  0.34698427]] (3, 3)


In [ ]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

NameError: ignored

In [ ]:
  L = 55//2
  m=55/2   
  print(L,m)

27 27.5
